### ISSUE TITLE
How to fix 'size' errors with '--enable-shm-snapshot'

### ISSUE THREAD

**Issue by bahaihe** [libvmi/libvmi#306] opened 2015-12-26 05:20 UTC
I want to use libvmi with Xen. And I run './configure --enable-shm-snapshot' about libvmi which is gited from GitHub.  When I run 'make', there are three errors in driver/xen/xen.c, they are 'struct vmi_instance' has no member named 'size':
(1) 66: if (paddr + length > vmi->size)
(2) 345: void* padding_mem = malloc(vmi->size)
(3) 2607: size_t max_size = vmi ->size - (paddr - 0)
I try to replace 'size' with (1) max_physical_address, (2) allocated_ram_size, (3) max_physical_address and run 'make' successfully. But I don't know whether it is right. Thank you.

**Comment by awsaba** [comment] 2015-12-28 16:53
Closing as a duplicate of #302.  Further discussion of the issue can be included there.

**Closed by awsaba** 2015-12-28 16:53 UTC
