### ISSUE TITLE
issue in ./configure command after patch

### ISSUE THREAD

**Issue by TahirAhmed916** [libvmi/libvmi#324] opened 2016-03-29 04:46 UTC
when i execute the command ./configure after the patch command following result came.
test@ubuntu:~/qemu-kvm-0.14.0$ patch -p1 < ../kvm-physmem-access_0.14.0.patch
patching file monitor.c
patching file qmp-commands.hx
patching file Makefile.target
patching file memory-access.c
patching file memory-access.h

test@ubuntu:~/qemu-kvm-0.14.0$ ./configure

Error: libpci header check failed
Disable KVM Device Assignment capability.

Install prefix    /usr/local
BIOS directory    /usr/local/share/qemu
binary directory  /usr/local/bin
config directory  /usr/local/etc
Manual directory  /usr/local/share/man
ELF interp prefix /usr/gnemul/qemu-%M
Source path       /home/test/qemu-kvm-0.14.0
C compiler        gcc
Host C compiler   gcc
CFLAGS            -O2 -g 
QEMU_CFLAGS       -m64 -D_FORTIFY_SOURCE=2 -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -Wstrict-prototypes -Wredundant-decls -Wall -Wundef -Wendif-labels -Wwrite-strings -Wmissing-prototypes -fno-strict-aliasing  -fstack-protector-all -Wmissing-include-dirs -Wempty-body -Wnested-externs -Wformat-security -Wformat-y2k -Winit-self -Wignored-qualifiers -Wold-style-declaration -Wold-style-definition -Wtype-limits
LDFLAGS           -Wl,--warn-common -m64 -g 
make              make
install           install
host CPU          x86_64
host big endian   no
target list       x86_64-softmmu
tcg debug enabled no
Mon debug enabled no
gprof enabled     no
sparse enabled    no
strip binaries    yes
profiler          no
static build      no
-Werror enabled   no
SDL support       yes
curses support    yes
curl support      yes
check support     no
mingw32 support   no
Audio drivers     oss
Extra audio cards ac97 es1370 sb16 hda
Block whitelist   
Mixer emulation   no
VNC TLS support   yes
VNC SASL support  yes
VNC JPEG support  yes
VNC PNG support   yes
VNC thread        no
xen support       no
CPU emulation     yes
brlapi support    no
bluez  support    no
Documentation     no
NPTL support      yes
GUEST_BASE        yes
PIE user targets  no
vde support       no
IO thread         no
Linux AIO support yes
ATTR/XATTR support yes
Install blobs     yes
KVM support       yes
KVM PIT support   yes
KVM device assig. no
fdt support       no
preadv support    yes
fdatasync         yes
madvise           yes
posix_madvise     yes
uuid support      yes
vhost-net support yes
Trace backend     nop
Trace output file trace-<pid>
spice support     no
rbd support       no
xfsctl support    no

**Comment by TahirAhmed916** [comment] 2016-03-29 07:48
after that when i use make command following error occurred:
GEN   config-host.h
  GEN   trace.h
  GEN   trace.c
  GEN   config-target.h
  LINK  x86_64-softmmu/qemu-system-x86_64
../slirp/misc.o: In function `memset':
/usr/include/x86_64-linux-gnu/bits/string3.h:81: warning: memset used with constant zero length parameter; this could be due to transposed parameters
/usr/bin/ld: ../qemu-timer.o: undefined reference to symbol 'timer_settime@@GLIBC_2.3.3'
//lib/x86_64-linux-gnu/librt.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [qemu-system-x86_64] Error 1
make: *** [subdir-x86_64-softmmu] Error 2

**Comment by tklengyel** [comment] 2016-04-13 04:03
Sounds like you don't have the proper build environment setup for compiling qemu. Verify first that you can compile vanilla qemu, then if that works compile the patched version.

**Comment by tklengyel** [comment] 2016-08-23 18:16
I assume this problem has been fixed since, so I'm closing this issue for now. Feel free to reopen it if the problem is still current.

**Closed by tklengyel** 2016-08-23 18:16 UTC
